### ISSUE TITLE
2.4 STL Errors Reported in slicer.

### ISSUE THREAD

**Issue by telxoid** [VoronDesign/Voron-2#125]
Loaded most of the 2.4 STL's currently available--found 4 throwing minor errors in PrusaSlicer.  I think someone else was saying Cura was throwing errors as well.
Gantry/Front_Idlers:

front_idler_right_upper.stl
front_idler_right_lower.stl
front_idler_left_upper.stl
front_idler_left_lower.stl

Thanks!

**Comment by Maglin** [comment]
I've noticed this since long before release.  If you reexport them from source they will give the same manifold errors.  The parts don't have any problems slicing in any of the big three slicers.  Going to leave open for prudence.

**Comment by FHeilmann** [comment]
Fixed by #198
