### ISSUE TITLE
Belt misalignment in F3D assembly v2.4

### ISSUE THREAD

**Issue by eholley** [VoronDesign/Voron-2#140]
Yikes! Belt A is offset a bit from the idler pulley. Left and right sides show a similar issue. I was planning on 3D printing my belt, so good thing I caught this! ;)

![Screen Shot 2020-05-20 at 10 35 18 PM](https://user-images.githubusercontent.com/946105/82523946-cff22880-9aea-11ea-8e10-56d1a32bba42.jpg)

![Screen Shot 2020-05-20 at 10 28 17 PM](https://user-images.githubusercontent.com/946105/82523950-d08abf00-9aea-11ea-80c8-876af8f19898.jpg)

![Screen Shot 2020-05-20 at 10 28 51 PM](https://user-images.githubusercontent.com/946105/82523948-d08abf00-9aea-11ea-98ab-6e7a1a2040c9.jpg)

**Comment by FHeilmann** [comment]
The belt CAD should not be used for anything other than a guide on where the belt is supposed to go. The belt in the CAD as it is is a finicky beast so we're not going to fix this minor issue at this time.

Bests,
-Florian
