### ISSUE TITLE
Parts are loose in v2.4

### ISSUE THREAD

**Issue by yhaiovyi** [VoronDesign/Voron-2#141]
There's 0.1 mm expansion compensation put directly into cad files. Now all parts I have already printed on a calibrated machine go into trash. So my proposal would be to add compensation as a variable, or just don't compensated at all, because that's not the right way to solve printing issues that some users might experience. CAD sizes should be precise.

**Comment by yhaiovyi** [comment]
A few examples:
- Bondtech axial bearing is 8mm. The corresponding hole size in CAD is 8.2mm.
- Z drive bearing is 14mm. The corresponding arcs sizes are 14.3mm!

Moreover it seems like compensation is not consistent, and meant to fix issues with some particular printer/filament.

**Comment by yhaiovyi** [comment]
Now my own experience.  I never worked with materials that would give that bad expansion. The biggest expansion compensation I've ever done was 0.09mm, and most certainly not 0.15mm. 0.15mm is severe over extrusion.

**Comment by Maglin** [comment]
.2-.3mm is standard ABS compensation for ABS shrinkage.  Some parts are designed for a sliding fit and not a press fit that would end up breaking the part from the stresses.

You never said what material you are using but every functional part of the Voron 2 printer is designed for ABS.  

Closing as this is as designed.
