### ISSUE TITLE
Voron 2.4 manual - hot end polarity note

### ISSUE THREAD

**Issue by pkuyken** [VoronDesign/Voron-2#152]
From page 119 of the v2.4 manual:

HOT END POLARITY
The hot end heater does care how you
wire it. The diagram above is simply
showing the terminal polarity of the
controller

Should that say "The hot end heater does not care how you wire it."?

**Comment by insurgus** [comment]
I'll clarify this in the next update.

**Comment by insurgus** [comment]
Updated in draft.
