### ISSUE TITLE
V2.4 Manual Correction

### ISSUE THREAD

**Issue by origuy42** [VoronDesign/Voron-2#161]
Page 27 appears to have two minor errors that may cause new builders slight confusion (like me!). They are easily overcome, and maybe it's just me, but clear/correct instructions >mostly correct instructions:

1) The M5x30 SCHS in the 'eyeholes' are mislabeled (at least according to the CAD file). Should be labeled BCHS instead. Not sure if there are clearance issues here, but consistency between the manual, BOM and CAD is probably a good thing.

2) The order of assembly on the page is physically impossible. The M3x16 SCHS can't go in before the lower printed part.

**Comment by Luddi1** [comment]
Another minor thing I spotted: On Page 59 you need a M3x30 instead of M3x20.

**Comment by kauedg** [comment]
In the Introduction's "Final Thoughts" the text is incomplete.

![Screenshot_20200716_154755](https://user-images.githubusercontent.com/31520323/87710171-c8ae6a80-c77b-11ea-829d-214fce0845e6.png)

**Comment by kauedg** [comment]
![Screenshot_20200722_142720](https://user-images.githubusercontent.com/31520323/88208444-9b543780-cc27-11ea-9222-a639e21fe1ce.png)

**Comment by insurgus** [comment]
> 
> 
> Another minor thing I spotted: On Page 59 you need a M3x30 instead of M3x20.

I think this was already resolved. The page numbers are all whacky now due to addition of sections. The carriage fasteners were updated to M3x30 some time ago though.

**Comment by insurgus** [comment]
> 
> 
> In the Introduction's "Final Thoughts" the text is incomplete.
> 
> ![Screenshot_20200716_154755](https://user-images.githubusercontent.com/31520323/87710171-c8ae6a80-c77b-11ea-829d-214fce0845e6.png)

This has been fixed.

**Comment by insurgus** [comment]
>     1. The M5x30 SCHS in the 'eyeholes' are mislabeled (at least according to the CAD file). Should be labeled BCHS instead. Not sure if there are clearance issues here, but consistency between the manual, BOM and CAD is probably a good thing.

Fixed.

**Comment by insurgus** [comment]
>     2. The order of assembly on the page is physically impossible. The M3x16 SCHS can't go in before the lower printed part.

Need clarification on this.
