### ISSUE TITLE
[V2.4] Instruction manual - missing step how to attach din rails with electronics to frame

### ISSUE THREAD

**Issue by lazymaniac** [VoronDesign/Voron-2#163]
Hey,

Instruction is missing step with DIN rail mounting.

Thanks

**Comment by hernsl** [comment]
Second this. It wasn't immediately obvious for a first time builder (@hernsl Discord) how deck pannel retention would work. A quick search on Discord shows it's an _extrusion | deck pannel | din rail_ sandwich.

**Comment by insurgus** [comment]
Sandwich page added to the start of the deck panel installation series.

**Comment by claytono** [comment]
@insurgus I'm new to the project.  Where are these updates going?  I don't see them in the repo or website.
