### ISSUE TITLE
[V2.4] Spool holder too short to fit Amazon Basics PLA spools

### ISSUE THREAD

**Issue by msharp58** [VoronDesign/Voron-2#165]
Current spool depth for Amazon Basics filament is 76mm.  The spool holder in its current state supports a maximum depth of about 73mm.  This is easily fixed by scaling along the x axis during print, but it might be worth lengthening it in the CAD and STL files.

**Comment by Lefuneste83** [comment]
You are correct. There is a User Mod for a wider spool holder that I have printed as my 3DJake spools wouldn't fit on the regular spool holder.
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/raymondh/LargeSpoolHolders

**Comment by insurgus** [comment]
Usermod recommended. Closing.
