### ISSUE TITLE
[V2.4] Manual text typo -- Introduction / Final Thoughts

### ISSUE THREAD

**Issue by benfoden** [VoronDesign/Voron-2#170]
[![Screenshot from Gyazo](https://gyazo.com/f43c4a4eabe4afb1472f2b716ac5fdeb/raw)](https://gyazo.com/f43c4a4eabe4afb1472f2b716ac5fdeb)

>VORON printers are amazing machines that take care and attention to assemble. Take your time! Little issues in the assembly phase tend to stack up and cause you trouble later on. If at any point you get stuck or are just not sure about something, please ask on Discord. There are

**Comment by insurgus** [comment]
Box boundary needed to be expanded. This has been resolved.
