### ISSUE TITLE
[V2.4] Manual Build plate (P31++)

### ISSUE THREAD

**Issue by kage-chan** [VoronDesign/Voron-2#171]
Hi,

the build plate in the assembly manual does not match the other drawings supplied through git.

1)  The mounting holes in the build plate in the manual are slotted holes, not round holes as in the bed drawings supplied.
2)  Thermal fuse location ind manual does not match location in bed drawings.
3) Bed ground not mentioned in anywhere in the manual

Nothing really severe, but a bit confusing :)

**Comment by insurgus** [comment]
The manual shows the best of the best, in this case a machined bed. It's a quality of life thing but you'll be just fine using the drilling template.

A ground option has been added to the manual.
