### ISSUE TITLE
[2.4] Manual Inconsistencies for Completed AB Drive Units section

### ISSUE THREAD

**Issue by hernsl** [VoronDesign/Voron-2#175]
- The image for the section titled _COMPLETED AB DRIVE UNITS_ reflects the _Z Belt Clips_ are installed. That step does not occur until 9 pages later in the section titled _ATTACH AB MODULES_.

- The image shows the Z Chain Retainer Bracket fixed in place on the A Drive Module in the aforementioned section, as well as in the section _A DRIVE MODULE + CHAIN ANCHOR._ This component does not appear to stay put until the cable chain is attached.

**Comment by insurgus** [comment]
Added a note regarding chain mount on pg 43.
