### ISSUE TITLE
Incorrect Bowden fitting in sourcing guide

### ISSUE THREAD

**Issue by shiftingtech** [VoronDesign/Voron-2#179]
The sourcing guide link (V2.4 tab, line 73) for a bowden fitting goes to the embedded bowden fitting as used in Jetpack, rather than the threaded one used in the V2.4 Exhaust assembly.

**Comment by translucentfocus** [comment]
I just looked into this and can confirm @shiftingtech discovery.


**Recommended Addition to the Voron 2.4 Sourcing Guide Tab**

| Category | Component                | Qty | Recommended                        | Alternative Source                                       |
|----------|--------------------------|-----|------------------------------------|----------------------------------------------------------|
| Bowden   | Threaded Bowden Coupling | 1   | [McMaster-Carr](https://www.mcmaster.com/5449K171/) |  [E3D](https://e3d-online.com/products/threaded-bowden-coupling) |

Btw, I think this is a brilliant ~use~ **recycling** ♻ of parts from back in the 2.1 days 👏

I checked the following sourcing guides and the part is not listed on any of them:
❌ Voron 2.4 Sourcing Guide
❌ Afterburner Sourcing Guide
❌ Mobius 3.1 Sourcing Guide
❌ JetPack Sourcing Guide

**Image taken from the latest [Voron 2.4 Manual](https://github.com/VoronDesign/Voron-2/blob/d95e46bccafb30359df9da4fc87642e3ce0d2acc/Docs/2.4_Assembly_Manual.pdf)**  from 2020.08.05 update
![image](https://user-images.githubusercontent.com/26986716/93162400-57872700-f6da-11ea-8c8e-96e053fda5c9.png)

**Comment by FHeilmann** [comment]
Thanks guys, should be fixed now. If not, feel free to reopen this!
