### ISSUE TITLE
2.4 BOM is short 3x M5x16 bolts

### ISSUE THREAD

**Issue by jrosen9** [VoronDesign/Voron-2#186]
I ran the configurator for a direct feed, 300mm with Misumi corner cubes.  The produced BOM stated I needed 11 M5x16 screws.  Following the manual, I have needed 14 of these of these screws

**Comment by julianschill** [comment]
It is actually short on 4x M5x16. In the manual there are 2 on page 51, 4 on page 52, 4 on 54, and 1 for the spool holder. Then you need 4 for the bed and 16 for the frame for blind joints. That makes 31 for blind joints and 15 for corner cubes.

**Comment by julianschill** [comment]
The BOM is indeed short of 4 M5x16. Here is an image of where the M5x16 are used: 
![VORON2_v2 4_Assembly_v1](https://user-images.githubusercontent.com/13122110/120026905-07938a80-bff3-11eb-9e1f-d8ef38c78260.png)

**Comment by cyrix2000** [comment]
Why is the BOM now showing just 11 M5x16 BHCS bolts?
