### ISSUE TITLE
Assembly_Manual Needs Version # Bump

### ISSUE THREAD

**Issue by translucentfocus** [VoronDesign/Voron-2#187]
Only creating this issue because I don't know of a way to do a pull request on the really well-done Assembly Manual 🙂 and figured this might help keep confusion to a minimum when users have older versions of the manual.

The latest and greatest **awesome** [Voron 2.4 Assembly_Manual is from 2020.08.05](https://github.com/VoronDesign/Voron-2/commits/Voron2.4/Docs/2.4_Assembly_Manual.pdf), but the [versioning inside the PDF](https://github.com/VoronDesign/Voron-2/blob/d95e46bccafb30359df9da4fc87642e3ce0d2acc/Docs/2.4_Assembly_Manual.pdf) wasn't updated 😢

Pinging @insurgus as it looks like you hold the keys to the PDF updates 😊

**Comment by insurgus** [comment]
This will be changed on the next release. It's currently sitting at 2020.09.25. Thanks!
