### ISSUE TITLE
[V2.4] Manual and Voron2_SKR_14_Wiring.pdf are inconsistent for A/B motor

### ISSUE THREAD

**Issue by elpopo-eng** [VoronDesign/Voron-2#190]
Hi,

The manual and Voron2_SKR_14_Config.cfg indicate connection of motor B on X and motor A on Y.
![image](https://user-images.githubusercontent.com/68954733/95326704-45487500-08a3-11eb-878d-4722e565867d.png)
![image](https://user-images.githubusercontent.com/68954733/95326737-55f8eb00-08a3-11eb-832c-25aa4d626cf4.png)

But in Voron2_SKR_14_Wiring.pdf the motors are inverted
![image](https://user-images.githubusercontent.com/68954733/95326767-614c1680-08a3-11eb-87c7-b927c118ee93.png)

Thanks

**Comment by mateuszbrzezinski** [comment]
I had same issue.
The other issue is that the extruder by default has wrong direction, at least 2 persons (including me) had to update the configuration to make it work.

**Comment by insurgus** [comment]
Updated. Will PR shortly.
