### ISSUE TITLE
[V2.4] Assembly Manual and Voron2_SKR_14_Wiring.pdf are inconsistent for A/B motor

### ISSUE THREAD

**Issue by elpopo-eng** [VoronDesign/Voron-2#191]
Hi,

The [Assembly Manual](https://github.com/VoronDesign/Voron-2/blob/Voron2.4/Docs/2.4_Assembly_Manual.pdf) and  [Voron2_SKR_14_Config.cfg](https://github.com/VoronDesign/Voron-2/blob/Voron2.4/firmware/klipper_configurations/SKR_1.4/Voron2_SKR_14_Config.cfg)
indicate connection of motor B on X and motor A on Y.
![image](https://user-images.githubusercontent.com/68954733/95326704-45487500-08a3-11eb-878d-4722e565867d.png)
![image](https://user-images.githubusercontent.com/68954733/95326737-55f8eb00-08a3-11eb-832c-25aa4d626cf4.png)

But in [Voron2_SKR_14_Wiring.pdf](https://github.com/VoronDesign/Voron-2/blob/Voron2.4/firmware/klipper_configurations/SKR_1.4/Voron2_SKR_14_Wiring.pdf) the motors are inverted
![image](https://user-images.githubusercontent.com/68954733/95326767-614c1680-08a3-11eb-87c7-b927c118ee93.png)

Thanks

**Comment by FHeilmann** [comment]
Since this is basically a clone of #190 I'm going to close this instance so we can focus our efforts there. Thanks for reporting!
