### ISSUE TITLE
Add motor diagram to manual

### ISSUE THREAD

**Issue by eddietheengineer** [VoronDesign/Voron-2#200]
Add the Z1-Z4, A/B, etc motor to the manual for easy reference

**Comment by simon-adriaanse** [comment]
For the SKR1.3 and 1.4 you can find them in firmware -> klipperconfigs -> skr version
[](https://github.com/VoronDesign/Voron-2/tree/Voron2.4/firmware/klipper_configurations)

**Comment by insurgus** [comment]
The motor information was removed so that things could be consolidated into the electronics manuals.
