### ISSUE TITLE
Error with STL [a]_60mm_fan_blank_insert_x2.stl

### ISSUE THREAD

**Issue by Edge540** [VoronDesign/Voron-2#201]
Hello, i am unable to print the file. Simplify3D or Prusaslicer bug with this file ( binary Stl error) . When clicking ion the Github file , it don't appear in the windows
Thank's

**Comment by karlla1220** [comment]
Sama as here.

**Comment by raymondh2** [comment]
See PR #198

**Comment by karlla1220** [comment]
> See PR #198

Thanks!

**Comment by FHeilmann** [comment]
Fixed by #198
