### ISSUE TITLE
Back Panel Drawing Missing Dimension Constraints

### ISSUE THREAD

**Issue by delos19** [VoronDesign/Voron-2#207]
The drawing for the back panel in the Drawings file currently has missing constraints for the exhaust cutout. A dimension in the X direction would lock in the location of the cutout, as it currently is missing a label for this and leaves the cut unfixed in all degrees of freedom. 

Possible fixes:

- Note stating cut is centered on panel size.
-  Call-out for distance in reference to frame width.

**Comment by nemgrea** [comment]
PR #216 fixes this issue
