### ISSUE TITLE
STEP files missing skirts for other sizes

### ISSUE THREAD

**Issue by luksok** [VoronDesign/Voron-2#211]
I'm trying to mod the printer a bit using CAD other than F360, After importing the step file to my CAD it appears to be 250mm version (not the 350 I have built). I tried to overcome this by installing F360 to open the CAD file but I can't see any way to convert the original file to 350mm version. Is there any chance you could give us 350mm STEP file? Thanks in advance!

**Comment by raymondh2** [comment]
We only model the 250mm frame. The skirts for the other models are included in the F360 file and likely the STEP as well. Let us know if those skirts are not included with the step file
