### ISSUE TITLE
RE:  M4 Knurled nut for bed

### ISSUE THREAD

**Issue by bigjoe4265** [VoronDesign/Voron-2#214]
In the Assembly .pdf (page 35) and BOM for the 2.4 you have a M3x16 SHCS (.5mm thread pitch) screwing into a M4 knurled nut (.7mm thread pitch) to anchor the bed.  Shouldn't this be an M3 knurled nut (thread pitch is .5mm)?

**Comment by raymondh2** [comment]
No this needs to be m4 as we aren't using fit as a nut, just a space.

**Comment by bigjoe4265** [comment]
> 
> 
> No this needs to be m4 as we aren't using fit as a nut, just a space.

Do you mean for thermal expansion or height of the thumb screw.  It's roughly .008 of an inch height difference between the M4 and M3 thumb nut.  The concern of course is stripping the screw due to the difference in thread pitch.

**Comment by raymondh2** [comment]
It's being used as a spacer. Not as a nut.
