### ISSUE TITLE
V2.4 Wrong dimensions of panel DXFs

### ISSUE THREAD

**Issue by dukeduck1984** [VoronDesign/Voron-2#218]
Hi,

I opened the DXFs with Dassault eDrawings and measured the dimension, and found out that the dimensions in the following files were wrong:

`Bottom_Panel_250.dxf`
`Bottom_Panel_300.dxf`
`Bottom_Panel_350.dxf`
`Deck_Panel_250.dxf`
`Deck_Panel_300.dxf`
`Deck_Panel_350.dxf`

The dimensions in `Back_Panel_xxx.DXF` are correct though.

**Comment by nemgrea** [comment]
Please make sure you are measuring from end to end. There are 2mm radii on the corners. Also make sure your import settings are correctly set to mm.
