### ISSUE TITLE
v2.4 A/B motor cable orientation in manual

### ISSUE THREAD

**Issue by x4242** [VoronDesign/Voron-2#220]
![image](https://user-images.githubusercontent.com/44498216/111302155-f5888980-864a-11eb-8ddb-fbe3de21d4ad.png)
The manual is showing the A/B motors mounted in a way that the cables/connectors are facing backwards. This leads to a potential collision with the back panel, resp. re-orienting the motors after assembly. It would be helpful (esp. for 1st time builders) to either change the manual drawing or give any form of hint.

**Comment by a1co** [comment]
I discovert the same issue

**Comment by FHeilmann** [comment]
Fixed in CAD, manual tbd.

**Comment by insurgus** [comment]
New renders are added to staging.
