### ISSUE TITLE
Really Loud Z-motors

### ISSUE THREAD

**Issue by oliclarke** [VoronDesign/Voron-2#232]
Hello, Ive been speaking to few people with this same issue.
Z motors are really loud . Using a range of boards, drivers and motors the problem persists. 
For some its Only present during firmware moves, i.e homing from the menu, for others is persistent in all movement on all axis. 
I have tried dropping the vref, forcing stealthchop, and increasing steps.  Nothing changes, all these changes have been tested with and without any belts on the Z.

Is there anything to check that could explain this?

**Comment by raymondh2** [comment]
The best place to get help on this is the Voron Design Discord. https://discord.gg/voron

**Comment by insurgus** [comment]
As per discord suggestion, closing issue.
