### ISSUE TITLE
Too many GT2 20T idlers on X-Axis (V2.4)

### ISSUE THREAD

**Issue by HandMadeTools** [VoronDesign/Voron-2#239]
In the X-Axis sub-group of the step files, (XYJoint-Left and XYJoint-Right) you have a GT2 20T Gates Idler V2 and a GT2 20T Idler V3 overlaid on top of each other. The V3 version does not fit within the body dimensions whereas the V2 does. I've attached a screen shot for convenience.

![Voron2_2 4_Assembly](https://user-images.githubusercontent.com/84644218/119240837-bf87ea00-bb52-11eb-99e1-e68037dfa028.png)

**Comment by stvptrsn** [comment]
That is modeled with both the generic idlers and the Gates idlers is why it looks like that.

**Comment by HandMadeTools** [comment]
Ok, noted with thanks!
