### ISSUE TITLE
Probe malfunctioning crash prevention routine

### ISSUE THREAD

**Issue by no-mana** [VoronDesign/Voron-2#242]
I was motivated to implement a simple routine to prevent a crash due to a dead probe when, after G28, I saw my printer dig into the bed doing the QGL. I found out that the probe was not working after just 1 month of use (mainly doing meshing to solve my bed flatness issues). 

I believe this is something that might be useful for others considering the doubtful QC and disparity of the probes used with the Voron 2.X.

The idea is to home (G28) then query the probe at a safe position/height where it is known to trigger. Check if it triggered, if not raise error. Takes less than 10 sec.

Is this something PR worthwhile?

**Comment by a1co** [comment]
That sounds like a good idea. I cannot check now, but i belive my probe sould light ub when the z endstop is triggert. Then that would not cost any additional time.

**Comment by julianschill** [comment]
This can be done with a macro. Check my CHECK_FLEXPLATE macro here: https://github.com/julianschill/CeBe_config/blob/cafaae847d028ac051ec81ee0b90436a6cc46ce3/macros.cfg#L66

**Comment by a1co** [comment]
> 
> 
> That sounds like a good idea. I cannot check now, but i belive my probe sould light ub when the z endstop is triggert. Then that would not cost any additional time.

That was nonsense: The z endstop is behind the bed. But there could still be a screwhead for probe testing placed.

**Comment by no-mana** [comment]
> 
> 
> This can be done with a macro. Check my CHECK_FLEXPLATE macro here: https://github.com/julianschill/CeBe_config/blob/cafaae847d028ac051ec81ee0b90436a6cc46ce3/macros.cfg#L66

Yup, that's exactly what I meant by routine (including a macro that does the check in the config). IMO, it'd be a good thing to add in the doc (maybe like a "safety" configuration section?) I've seen a few user in the discord losing their probe and digging a nice hole in the plate. The homing sequence could also be done at lower Z current which would help prevent catastrophic issue  in case your forget to put the Z pin, the head got stuck somewhere during the homing and it's not underneath the Z pin / other bad luck, etc.

**Comment by raymondh2** [comment]
Inactivity
