### ISSUE TITLE
AB Idler Belt Wear

### ISSUE THREAD

**Issue by chrisingham05** [VoronDesign/Voron-2#255]
I have a suggestion for improving the AB front idlers as I've had some damage to my belts due to how they are designed. Currently, the idlers are tightened using a screw at the front which are aligned to the centre of the idler, however as the belt idler is either at the top or bottom depending on which side it sits this creates a rotational force which mis-aligns the idler bearing giving it a slight angle. This angle causes the belt to rub at one end causing wear to the belt. I suggest moving the screw so that it is in line with the centre of the idler bearing so that there is no rotational force. For my printer, I plan to make a few spacer wedges that I can stick in the idler to stop this rotation, but just moving the tensioner screw in the design would fix this quite easily. Only downside is it would not look symmetrical from the front.

![idler](https://user-images.githubusercontent.com/75641124/129440354-e07bfa2e-8b54-4c8e-9190-5d5cc9f9e6e0.png)

**Comment by chrisingham05** [comment]
Slight damage to the belt found so far

![image1](https://user-images.githubusercontent.com/75641124/129440436-4695fa07-e8a0-4009-8cec-0295e1e2567b.jpg)

**Comment by chrisingham05** [comment]
Temporary solution is to measure the gap between the red carriage and back of the idler with callipers to see the distance when the belts are tensioned, then printed small spacer blocks for each side to align the red carriage. Using one block at the end of where the belt meets allowed me to change the angle of the red carriage by tightening or loosening the screw. Appears to have improve the situation for now. Obviously on the right the block is at the top and on the left the block is at the bottom. Note, the picture is the correct way up, I assembled the red carriage upside down but that doesn't affect the printer or this issue. 


![carriage](https://user-images.githubusercontent.com/75641124/129707758-39ad657d-7ea7-456a-baf8-75c188badce3.jpg)

**Comment by ServAlex** [comment]
I also experience this issue on B belt, haven't verified culprit yet

![image](https://user-images.githubusercontent.com/6973660/129716310-fbe0ec5d-6a71-4961-ba7f-eefad1af5984.png)

**Comment by yonkiman** [comment]
I have the exact same wear issues around front idlers on A and B belts.  Your explanation sounds right - may try to address by twisting idler frame forward or backward before clamping down with vertical pin.  Would like to address before I re-belt…

**Comment by chrisingham05** [comment]
Since fitting the spacer blocks I've not noticed any more wear on the belts

**Comment by 1ucket** [comment]
Have the same issue, for me it even cut a notch into the belt through which it is now leaving the idler.
![DSC_0039](https://user-images.githubusercontent.com/20580921/132216166-ccd9c52e-111c-4cde-bdbd-4a288aeb1d8a.JPG)

**Comment by DanJunior78** [comment]
Would be a good idea to redesign it, as you mentioned, test it and do a pull request.
I'll soon build my second V2 and i could also try it.
In my first I've same issues.

**Comment by ServAlex** [comment]
> Have the same issue, for me it even cut a notch into the belt through which it is now leaving the idler.
> ![DSC_0039](https://user-images.githubusercontent.com/20580921/132216166-ccd9c52e-111c-4cde-bdbd-4a288aeb1d8a.JPG)

this one is really strange, I don't know what part could do that, the only guess is the flange of the bearing, but to do that your belt have to be on top of it which would be quite noticeable

Ohh, I see a line in the middle of my belt too, guess it's where 2 bearings meet in the stack

**Comment by 1ucket** [comment]
> 
> 
> > Have the same issue, for me it even cut a notch into the belt through which it is now leaving the idler.
> > ![DSC_0039](https://user-images.githubusercontent.com/20580921/132216166-ccd9c52e-111c-4cde-bdbd-4a288aeb1d8a.JPG)
> 
> this one is really strange, I don't know what part could do that, the only guess is the flange of the bearing, but to do that your belt have to be on top of it which would be quite noticeable
> 
> Ohh, I see a line in the middle of my belt too, guess it's where 2 bearings meet in the stack

It would become nearly completely stuck in the rear left corner (aka the part where the belt would leave the idler). So yeah, it was quite noticeable.

**Comment by GadgetAngel** [comment]
> Temporary solution is to measure the gap between the red carriage and back of the idler with callipers to see the distance when the belts are tensioned, then printed small spacer blocks for each side to align the red carriage. Using one block at the end of where the belt meets allowed me to change the angle of the red carriage by tightening or loosening the screw. Appears to have improve the situation for now. Obviously on the right the block is at the top and on the left the block is at the bottom. Note, the picture is the correct way up, I assembled the red carriage upside down but that doesn't affect the printer or this issue.
> 
> ![carriage](https://user-images.githubusercontent.com/75641124/129707758-39ad657d-7ea7-456a-baf8-75c188badce3.jpg)

Where is the parametric .stl file for the red carriage spacer blocks that I can print out for when I do my Voron 2.4 build?  I really do not want to damage by High Temperature Gates Belts!

**Comment by chrisingham05** [comment]
I redesigned the A and B idlers to accommodate this change, will print and test. 

![IdlerNew](https://user-images.githubusercontent.com/75641124/138251009-2cedff4f-b168-4e66-8e75-ef2a253da111.png)

Not sure how or where to share the STLs though!

**Comment by DanJunior78** [comment]
Always on Voron User mods in GitHub

**Comment by 1ucket** [comment]
> 
> 
> I redesigned the A and B idlers to accommodate this change, will print and test.
> 
> ![IdlerNew](https://user-images.githubusercontent.com/75641124/138251009-2cedff4f-b168-4e66-8e75-ef2a253da111.png)
> 
> Not sure how or where to share the STLs though!

There's a [guide ](https://docs.vorondesign.com/community/support/pull_request_guide.html) on how to add your mods. As @DanJunior78 said just add it to VoronUsers/tree/master/printer_mods.

**Comment by chrisingham05** [comment]
> > I redesigned the A and B idlers to accommodate this change, will print and test.
> > ![IdlerNew](https://user-images.githubusercontent.com/75641124/138251009-2cedff4f-b168-4e66-8e75-ef2a253da111.png)
> > Not sure how or where to share the STLs though!
> 
> There's a [guide ](https://docs.vorondesign.com/community/support/pull_request_guide.html) on how to add your mods. As @DanJunior78 said just add it to VoronUsers/tree/master/printer_mods.

Thanks :) Not used github much! 

Created a pull request https://github.com/VoronDesign/Voron-2/pull/272

**Comment by DanJunior78** [comment]
No issues...it took me also 3 attempts to get my uploads approved. Basically you have to follow the rules which are mentioned.
1) preparing a readme with pictures, which you have.
2) printable without supports.

I could have tested it on my 2nd V2 which I'm building right now. Unfortunately I've passed this step already.
But i would be interested in the results. Did you try it already a certain time and could feedback here your results.
Out of the physical view, it has to be the solution.

**Comment by netweaver1970** [comment]
Another (more adjustable and skinnier solution) https://github.com/Ramalama2/Voron-2-Mods/tree/main/Front_Idlers

**Comment by GadgetAngel** [comment]
> Another (more adjustable and skinnier solution) https://github.com/Ramalama2/Voron-2-Mods/tree/main/Front_Idlers

yeah, I just found this suggestion.  Why doesn't Ramalama2 submit it to the VoronUsers mods branch?

I also see that Ramalama2 has the Front_Idlers offset for the GE5C mod and his design also uses a PIN in stead of a M5 bolt to align the idlers.  Thanks for the suggestion.

**Comment by DaddyBender** [comment]
Please excuse me if I don't have the terminology quite right.

I was going over the latest f3d, and I think I found belt-to-belt contact?  
Example:
If I remove the exterior parts to look at the idler bearings, it looks like the z belts are rubbing against the A/B (?) belts?

![image](https://user-images.githubusercontent.com/95513833/144695390-26e78c04-4d6a-43da-b4ca-ce42e2b206fa.png)

**Comment by GadgetAngel** [comment]
> Please excuse me if I don't have the terminology quite right.
> 
> I was going over the latest f3d, and I think I found belt-to-belt contact? Example: If I remove the exterior parts to look at the idler bearings, it looks like the z belts are rubbing against the A/B (?) belts?
> 
> ![image](https://user-images.githubusercontent.com/95513833/144695390-26e78c04-4d6a-43da-b4ca-ce42e2b206fa.png)

I was looking at the belts of the Voron 2.4 assembly model also.  If you look the belt path does not fit the idlers, I think the model has an error in it.  To redraw the belt path to make if fit as it should would take time. 

But I agree the model does show the belt path is off in places.

**Comment by Galifrey1965** [comment]
I reprinted my tensioners today so they fit tighter around the carrier and after nipping up the M5 bolt they sit square no problem. However, seeing as this is down to print tolerances and poor design, I can see how Chrisingham05's design is much better and avoids running the bolt through the split in the joined carrier. Overall I cannot help but wonder how the design team missed this as a potential weakness.
