### ISSUE TITLE
Fysetc Spider printer config file missing

### ISSUE THREAD

**Issue by jhollandb** [VoronDesign/Voron-2#257]
I noticed there is no section for the Spider printer config listed.  also the link from the Voron Documentations software configuration section link for the V2 Spider does not work anymore.  could you please provide a printer config file for USB?  thanks

**Comment by eduncan911** [comment]
Isn't that what #247 is for?

**Comment by kellybyrd** [comment]
Yup, PR #247  seems to solve this, but it was not merged, just closed. It looks like the new one is PR #261 ?

**Comment by eduncan911** [comment]
Correct, he just closed it yesterday and moved to a new PR.
