### ISSUE TITLE
 [V2.4] Manual Enhancement: Adding Comment on VHB, and some revamps.

### ISSUE THREAD

**Issue by khay8485** [VoronDesign/Voron-2#260]
Hello friendly Admin who reads this,

as i was in the last steps of building my V2 i found a page in the actual manual which i think could be added with an information that can be copy-pasted from a few pages before. Therefore i scrolled through the entire manual again to mark some spots that may be confusing.
- Page 23 shows the old motor mount, but i think you are aware of that.
- Page 34 shows the old printed part for the z endstop pin, maybe a comment about fitting should be added.
- On Page 78 lower left picture doesn´t belong there and can cause confusion. In addition the upper left pic on page 79 could be fitted to page 78 after deleting the wrong one. Then you would have a closed workstep.
- Maybe a hint on Page 99 that there are two different parts "belt_guard_**a**_x2.stl" and "belt_guard_**b**_x2.stl". They are only slightly different but if you know that they are, you can realize which to mount on each corner.
- Finally page 106, which shows mounting of the bottom panel. I assume there has to be VHB to fix the clips and latches to the panel? If so, just copy the comment on VHB from page 102. If not, a description on how to fix the hinges would be nice.

Nevertheless, thank you for all your time and effort to create and maintain such a detailed manual. 

greetings
khay

**Comment by simonaaker** [comment]
62 and 63 should switch order
