### ISSUE TITLE
some of the 350/300mm skirt parts are missing from the fusion 360/step files

### ISSUE THREAD

**Issue by sundansx** [VoronDesign/Voron-2#274]
I am trying to modify the rear Skirt B and in the fusion 360 2.4r1 file, the 300mm and 350mm skirt objects are missing. I thought that they may just be reused from another side, but I don't think that is the case, as those would be backwards.

![image](https://user-images.githubusercontent.com/25075847/140618570-bd741a24-35e3-4053-858f-441659e35e98.png)

**Comment by newphreak** [comment]
B is just A mirrored. So just mirror the part?

**Comment by sundansx** [comment]
hmm, good point...did not think of that.  thanks.

**Comment by sundansx** [comment]
resolved by mirroring.  I guess I expected that the parts were already there to be generated for the STL payload.
