### ISSUE TITLE
MkS Monster8hello is it possible to create a working printer.cfg for the mks monster

### ISSUE THREAD

**Issue by BOAndy1985** [VoronDesign/Voron-2#284]
hello is it possible to create a working printer.cfg for the mks monster

**Comment by raymondh2** [comment]
The dev team doesn't have one of these boards and likely won't be supporting it due to this. You best bet would be making your own configuration.

**Comment by BOAndy1985** [comment]
das würde ich auch machen aber ich finde nirgendwo wie man so eine Datei erstell .  und dann einen frage was bedeutet das ^ vor denn pins das!  zeichen heist ja invertirt

**Comment by raymondh2** [comment]
I suggest referring to the Klipper documentation https://www.klipper3d.org/Config_Reference.html
