### ISSUE TITLE
Fragile shaft

### ISSUE THREAD

**Issue by jack9603301** [VoronDesign/Voron-2#285]
Why can't we improve your shaft to increase its strength or reliability? I don't know if it often breaks due to printing problems. Can't we design our shafts as separate? Alternatively, a metal shaft is recommended.

During maintenance, it is often possible to open the door 180 degrees, which is easy to break in such a large angle and frequent operation.

**Comment by raymondh2** [comment]
Which shaft? There are many shafts used in the build. If you are refering to the Afterburner hinge it is adequet as is and we have not heard reports of it breaking when ABS is used as the pin

**Comment by jack9603301** [comment]
I mean the front door

> Which shaft? There are many shafts used in the build. If you are refering to the Afterburner hinge it is adequet as is and we have not heard reports of it breaking when ABS is used as the pin

**Comment by raymondh2** [comment]
This has not been an issue reported by anyone. I am closing this as a non issue

**Comment by julianschill** [comment]
There is also a Mod for hinges with M3 screws as shaft.
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/mosher/m3_door_hinges

**Comment by jack9603301** [comment]
> There is also a Mod for hinges with M3 screwsas shaft. https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/mosher/m3_door_hinges

Yes, plastic shafts must not be used for door shafts, which will cause problems

I'm watching.

https://voronregistry.com/mods/270_clampinghinges_alexandert-moss
