### ISSUE TITLE
Inconsistent cable types in BoM vs. sourcing guide

### ISSUE THREAD

**Issue by cpu601** [VoronDesign/Voron-2#303]
When using the Voron 2.4 configurator the downloadable version of the BoM differs from the sourcing guide when it comes to cables:

![image](https://user-images.githubusercontent.com/18030370/131790186-1fb1546c-9fd6-4d60-962e-b6db3c974b2b.png)

Left is the sourcing guide (which I assume is up to date), right the downloaded BoM generated by the configurator.

**Comment by raymondh2** [comment]
This has been fixed
