### ISSUE TITLE
generic cable chains documentation and bend radius

### ISSUE THREAD

**Issue by bubnikv** [VoronDesign/Voron-2#304]
1) Document how the generic chain should bend around the tool head. The chain shall not be allowed to bend sharply upwards at the tool head as in https://www.reddit.com/r/voroncorexy/comments/sn6f6f/voron_v24_serial_request_z_rex_8520/
Correct:
https://www.reddit.com/r/voroncorexy/comments/smz6ma/voron_24_serial_request_discord_homewerken0078/

The trick is that one end of the generic chains rotates freely while the other end's rotation is limited. The limited rotation end shall be mounted high while the freely rotating end shall be mounted to the aluminum extrusion.

2) The number of links for the generic cables is not documented. This likely costs many of us many hours trying to find out ourselves, or building incorrectly. Also please document how to open the chains, I pried couple of links violently breaking some of the latches before finding out that one shall use a small screwdriver to open the links.

3) The generic chains don't like to bend at such a sharp angle, at least those delivered with the Formbot kit. Also the Formbot provided PTFE cables are quite rigid. I don't like to break those expensive high quality cables by bending them sharply. I would rather sacrifice a centimeter or two of Z height for durability of X/Y cables. Thus I would like to get at least the X cable mounted higher. I am re-modeling the X cable mount to align the bottom of the mount with the top of the E motor and to add a zip tie mount for the E cables. The Y chain end is a bit higher than the X chain end, however the chain bends it upwards most of the time, thus the Y chain bends under a higher radius than the X chain. I would still like the Y chain to be mounted higher.

It may also be a good idea to use more links than usual. The X chain then would collide with the left rear Z idler at the very top position with Y above 300mm for my 300mm build, however one may configure Klipper to only move Y above 300mm when homing, thus avoiding this collision.

3) Offer a Z mount for the generic chains.

4) As mentioned in https://github.com/VoronDesign/Voron-2/issues/245 the sourcing guide does not specify enough of screws.

5) Update the manual to explain that a single screw is sufficient to mount the generic chains to the aluminum extrusions. This is already made clear in the Trident manual, which I suppose recommends the generic chains primarily.

**Comment by raymondh2** [comment]
Issues 1, 3#2, and 5 are being worked on for 2.4r2
Issue 2 is documented for Igus Chains but will not be for generic chains as it varies.
Issue 3#1 has not proved an issue with wires breaking when using PTFE
Issue 4 is already covered by another open issue.

I hope this answers your concerns
