### ISSUE TITLE
metal corners on frame?

### ISSUE THREAD

**Issue by bubnikv** [VoronDesign/Voron-2#306]
After adjusting the frame with blind joints carefully, I wonder whether the frame will not move at the blind joints when the quite heavy machine is transported multiple times.

I have seen a mod where aluminum corner joints were used in addition to blind joints.
https://jan-griffioen.synology.me/voron-2-4-corexy-printer-300x300mm/

![image](https://user-images.githubusercontent.com/5830947/152959674-5abc7655-b1d9-443a-8220-5a652693d607.png)

IMHO such reinforcement of the frame is quite valuable and not too expensive. Does it make sense?

https://www.aliexpress.com/item/4000929742684.html?spm=a2g0o.productlist.0.0.1ea7293cvj5kgM&algo_pvid=7e96671b-8f9b-496b-98e3-54943975c70e&algo_exp_id=7e96671b-8f9b-496b-98e3-54943975c70e-54&pdp_ext_f=%7B%22sku_id%22%3A%2210000011271009649%22%7D&pdp_pi=-1%3B3.27%3B-1%3B-1%40salePrice%3BUSD%3Bsearch-mainSearch

https://www.aliexpress.com/item/33041512892.html?spm=a2g0o.productlist.0.0.1ea7293cvj5kgM&algo_pvid=89e9553c-77f2-4b73-a595-d59d05322167&algo_exp_id=89e9553c-77f2-4b73-a595-d59d05322167-18&pdp_ext_f=%7B%22sku_id%22%3A%2267424572708%22%7D&pdp_pi=-1%3B9.05%3B-1%3B-1%40salePrice%3BUSD%3Bsearch-mainSearch

https://www.aliexpress.com/wholesale?trafficChannel=main&d=y&CatId=0&SearchText=2020+extrusion+corner+bracket&ltype=wholesale&SortType=default&page=1

**Comment by raymondh2** [comment]
As stock the current frame is quite rigid when tightened properly. And the printed parts offer indexing to keep the extrusions from twisting drastically.

**Comment by bubnikv** [comment]
> As stock the current frame is quite rigid when tightened properly. And the printed parts offer indexing to keep the extrusions from twisting drastically.

Also tightening the corner brackets may move the extrusions out of alignment.

Some of the corners are already occupied by rails and printed parts, thus not all of the 6x4=24 corners could be populated with a bracket.

**Comment by raymondh2** [comment]
This is something we don't think is needed by most builders. If it becomes an issue later on we can reopen this issue :)
