### ISSUE TITLE
2.4R2 Manual - few errors

### ISSUE THREAD

**Issue by BeardedTinker** [VoronDesign/Voron-2#312]
Page 185 of yet to be released R2 manual has error.
In title is states Controller Board while in a fact it's Solid State Relay.
![image](https://user-images.githubusercontent.com/47822612/154850379-c76dc290-4bb4-49b5-8282-e4c53837b48d.png)

Page 205 has title over title.
![image](https://user-images.githubusercontent.com/47822612/154850538-4055ab87-1bab-438c-9d3f-28a290a2eda1.png)

**Comment by evader** [comment]
Also page 6 & page 289 DOCS hyperlinks lead to https://docs.vorondesign.com/%20 404 error.
<img width="1255" alt="Screen Shot 2022-02-23 at 9 02 10 pm" src="https://user-images.githubusercontent.com/79675315/155324726-244cd606-3ade-438d-a659-5d7ca1a8d5e5.png">
![Screen Shot 2022-02-23 at 9 02 56 pm](https://user-images.githubusercontent.com/79675315/155324753-0e365cf8-f875-47fd-ab95-55b9453fbe35.png)
