### ISSUE TITLE
Release Notes V2.4r2 Part ID

### ISSUE THREAD

**Issue by Red-112** [VoronDesign/Voron-2#318]
I've read through the release notes for the Voron V2.4r2 and it would really help if the built point revisions had the STL part name in it or what exact parts it effects. For example; "Revised Z gantry blocks with extra material..." What parts are effected? This would help people who are currently building and people would what to update the Voron 2.4 builds.

**Comment by stvptrsn** [comment]
I put together a quick summary of parts that were changed.

https://docs.google.com/spreadsheets/d/1kPTQX1FffAdaUSn5Bqg3Sz63h_om7z8YBTyErquPfNM/edit?usp=sharing
