### ISSUE TITLE
First project

### ISSUE THREAD

**Issue by Tommy-gh** [VoronDesign/Voron-2#320]

**Comment by raymondh2** [comment]
Can you please provide more information on your issue?

**Comment by Tommy-gh** [comment]
No

**Comment by Tommy-gh** [comment]
Im joking

**Comment by DunarDolorgiet** [comment]
Looks to me like this issue was opened by mistakes. Closing it for now. When opening issues please make sure to provide information about the issue you're facing.

**Comment by Tommy-gh** [comment]
ok i sorry
