### ISSUE TITLE
Rear centre is about 4mm too big.

### ISSUE THREAD

**Issue by Macmagoo** [VoronDesign/Voron-2#322]
The Rear Centre Skirt is about 4mm too big it does not fit Voron 300.

**Comment by stvptrsn** [comment]
> The Rear Centre Skirt is about 4mm too big it does not fit Voron 300.

Hi Macmagoo, can you provide any pictures?  I've printed an installed the parts on a 300 build so I'd like to see if something else might be going on.

Steve

**Comment by Macmagoo** [comment]
Hi Steve, I hope the attached pictures help. It is my first Voron so perhaps it is something I have done. I am going to reprint it at some point today with a 4 mm reduction in length.

Thanks to the Voron Team for the work you all put into the design.

Regards

Andy

**Comment by stvptrsn** [comment]
> Hi Steve, I hope the attached pictures help. It is my first Voron so perhaps it is something I have done. I am going to reprint it at some point today with a 4 mm reduction in length. Thanks to the Voron Team for the work you all put into the design. Regards Andy
> […](#)
> On 27 Feb 2022, 04:56 +0000, Steve Peterson ***@***.***>, wrote: > The Rear Centre Skirt is about 4mm too big it does not fit Voron 300. Hi Macmagoo, can you provide any pictures? I've printed an installed the parts on a 300 build so I'd like to see if something else might be going on. Steve — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

The pictures do not appear to have come across. Are you on the Voron discord?  You can DM me there.  I doubt you need to re-print.  How do the side pieces line up?  Do you have the belt guards installed and are they pressed up against the Z drive modules? 

Steve

**Comment by Macmagoo** [comment]
![IMG_1944](https://user-images.githubusercontent.com/90116319/155869535-43d69b7d-8683-4d53-b3b6-7952dda32a63.jpeg)
![IMG_1943](https://user-images.githubusercontent.com/90116319/155869546-8771b893-60a4-4301-abaf-c1eece16713f.jpeg)

**Comment by Macmagoo** [comment]
I have attached them here.

**Comment by stvptrsn** [comment]
You have mismatched parts there.  The side opposite the power inlet is the old version or a front piece.  You need the keystone piece.

Steve

**Comment by stvptrsn** [comment]
![image](https://user-images.githubusercontent.com/46913624/155869604-9e863450-d07e-4c4f-b127-fbf1dc3fd973.png)

**Comment by Macmagoo** [comment]
> You have mismatched parts there. The side opposite the power inlet is the old version or a front piece. You need the keystone piece.
> 
> Steve

Sorry about that I will print the keystone part so that I can get on with my build.

Thanks for taking the time to reply.

Andy
