### ISSUE TITLE
Filename of the WAGO mount STL suggests it needs to be printed 5x

### ISSUE THREAD

**Issue by Traston** [VoronDesign/Voron-2#325]
Filename is 'wago_221-415_mount_3x5.stl'.  It will be easy for many to believe they need to print 5 copies of the part.

**Comment by SMTDesigns** [comment]
Recommend wago_221_415_3x_mount.stl for new name. The wago part number already defines a 5 position part. The only thing that would help if other wago parts are defined with a "number"x to define how many wago modules that print handles regardless of how many positions the actual wago part contains.

**Comment by stvptrsn** [comment]
Thanks. This makes sense and was suggested by some of the team as well.  It's queued up for an update and will be pushed with a couple more minor changes.

**Comment by J89eu** [comment]
Agreed, I've been printing 5, turns out you need one. At least I have stock! Confusing name.

**Comment by stvptrsn** [comment]
Hi J89eu, thanks for replying on this issue.  This was supposed to be included in the last updates pushed.  I'll work toward making sure it's updated.

**Comment by nemgrea** [comment]
fixed
https://github.com/VoronDesign/Voron-2/pull/419
