### ISSUE TITLE
Wrong names of stl joints

### ISSUE THREAD

**Issue by Muszek1996** [VoronDesign/Voron-2#331]
There's name of MGN12 in .stl files but they are actually for mgn9
xy_joint_right_upper_MGN12.stl
xy_joint_right_lower_MGN12.stl
xy_joint_left_upper_MGN12.stl
xy_joint_left_lower_MGN12.stl

**Comment by raymondh2** [comment]
The MGN12 denotes that those joints are for MGN12 on the X axis. Voron 2 doesn't support MGN12 on any other axis

**Comment by SMTDesigns** [comment]
just a further note on this. 2.4r1 uses the mgn9 for the x axis and 2.4r2 release changed this recently to mgn12 (all the others are still the mgn9). I just printed the r2 parts and they are definitely mgn12.

**Comment by stvptrsn** [comment]
I think the confusion was just in which axis the MGN12 referred to.  @Muszek1996 Now that that's cleared up I'm going to close this issue but if you need further clarification or anything let me know.
