### ISSUE TITLE
PSU Stabilizer installation page missing T-Nut

### ISSUE THREAD

**Issue by locki-cz** [VoronDesign/Voron-2#332]
PSU_stabilizer_50mm.stl
![image](https://user-images.githubusercontent.com/30490842/158996578-77d49587-7002-4585-85a2-f2b5e728fd4e.png)

This stl is wrong and doesnt fit. In Fusion model and in manual is correct part

![image](https://user-images.githubusercontent.com/30490842/158996880-e672378b-c818-4c78-89e0-792c8623a4b1.png)
[PSU_stabilizer_50mm.correct.zip](https://github.com/VoronDesign/Voron-2/files/8317961/PSU_stabilizer_50mm.correct.zip)

**Comment by SMTDesigns** [comment]
of note, the file above is not a zip file. Remove .zip from name to use.

**Comment by locki-cz** [comment]
fixed, now is stl in zip file

**Comment by bofh69** [comment]
What is that M5 screw screwed into?

**Comment by locki-cz** [comment]
> What is that M5 screw screwed into?

M5 T-nut

**Comment by matt-rendall** [comment]
Thank you!

**Comment by bofh69** [comment]
> M5 T-nut

That's not described in the manual
