### ISSUE TITLE
2.4r2 Manual - Missing Deck Support Installation Instructions

### ISSUE THREAD

**Issue by trainreth** [VoronDesign/Voron-2#334]
I searched the 2.4r2 manual but could not find a page describing how to install the deck supports that are included in the STLs here:

https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/Panel_Mounting/deck_support_3mm_x8.stl
https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/Panel_Mounting/deck_support_4mm_x8.stl

**Comment by DunarDolorgiet** [comment]
The parts are optional and are usually skipped when building the printer. Place the key looking bit in the extrusion slot and rotate 90° clockwise.
