### ISSUE TITLE
2.4r2 manual - missing heatset instructions.

### ISSUE THREAD

**Issue by StevensStuff** [VoronDesign/Voron-2#338]
There are no instructions on preparing the skirt pieces https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/Skirts/side_fan_support_x2.stl to add the required heatset insert.
Should probably be placed around page 242 with adding the heatset to the other skirt pieces.

**Comment by SMTDesigns** [comment]
just a thought, why not make HELP section at the end of the manual where anything that is so general as to apply to all printers can be placed. Heatset inserts apply to all printers, extruders, etc. You can maintain one help section that can be tacked on to any thing that needs the information. Start with thermal inserts and maybe the GT2 pulleys to highlight the use of loc-tite.  The places where help is needed then add a pointer to the page.  I have written a few assembly manuals for my products and always had separate docs for things that were used in more than one product that people may need help with.
