### ISSUE TITLE
2.4r2 manual power supply confusion

### ISSUE THREAD

**Issue by LoganFraser** [VoronDesign/Voron-2#340]
The manual on page220 has 3 sets of wires connecting to the inputs on the octopus, and appearing to be spliced together. This in not best practice, as the 3 output terminals on the power supply are not recommended to have the entire load on a single terminal screw pair. Please update the drawing with the following, that removes the redundant wiring to BED-Power and shows direct connections to the Mot-Power-in and Power-In.  
![2 4r2page220](https://user-images.githubusercontent.com/33788254/160246038-50f20207-e6d3-4109-b246-7dc3f9847b17.png)

**Comment by julianjc84** [comment]
This is how I wired mine too, My kit came with larger gauges of wire that was used to connect to the motors power tab too.

**Comment by julianjc84** [comment]
I also found the orientation of the SSR on page 213 and on page 211 confusing.
page 213 shows load side and active wiring. on NO2
page 211 shows the Active to bed Reversed on NO1
![211 active](https://user-images.githubusercontent.com/14962510/160735232-8f3d7973-98c8-46d9-8847-f3fc9e7e8330.png)
![213 active reversed](https://user-images.githubusercontent.com/14962510/160735242-4ddc6c46-ad73-416a-ac50-4feaddce9bd3.png)
.

**Comment by LoganFraser** [comment]
This isn't fixed though?  The diagram still shows junctioned wires instead of parallel ones and connection to BED POWER when BED OUT isn't used in the wiring diagram.
