### ISSUE TITLE
Using unsafe and untested parts on BOM

### ISSUE THREAD

**Issue by ghost** [VoronDesign/Voron-2#345]
This comment was marked as disruptive content and therefore edited. The original comment is still available with GitHubs versioning

**Comment by SMTDesigns** [comment]
Please pass on the test results to the community here, so we can look at what you have done. Also, point out what parts specifically do not have certificates rather than just sending a general list of negative comments. The screen shot you made would be helpful also. Thank you.

**Comment by ghost** [comment]
Oh looks a rocket designer to vorons rescue, do you use a voron by any chance... maybe you should do the tests close my case

Why have you a website that's last updated in 2019

**Comment by bdbell** [comment]
Actually, it's a really common part of the accepted scientific method to ask for someone else's test results as a starting point for proving or disproving something.  He is one of the designers and is openly looking for the evidence you have in order to start his investigation. If you have legitimate test results then please provide them as it would be helpful.

**Comment by DrDMo** [comment]
Dude, just leave.

**Comment by ghost** [comment]
I don't have any of them I have sent them to the British standards in the UK to be investagated unlike the US we have powered to have item imported investagated for safety and the cases banned from entering the country 
And also by sending him information is breach of my privacy and trying to collect data and risk my family

**Comment by bdbell** [comment]
> I don't have any of them I have sent them to the British standards in the UK to be investagated unlike the US we have powered to have item imported investagated for safety and the cases banned from entering the country 

I look forward to seeing the results.

**Comment by ghost** [comment]
Github is unsafe to post personal information 
As of this I will not be sending anything

I am posting to mind other that using aliexpress is unsafe very small procent of electronic are tested and just has a shiny sticker them can be get from ebay

**Comment by ghost** [comment]
I will not be responding again

**Comment by ghost** [comment]
Sorry SMTDesign
I want to ask i have looked at your profile have seen someone posts that you are one of the designers but i dont see that you are very active
Why is that may I ask?

Also as a electronic designer  Why have you know fabucated your own boards

I have designed my own CAN bus toolhead pcb for the stealthburner that go's just behind the part cooling fan with a spacer that make the SB around 4mm forward that the stock also has filament length sensor and also ercf filament flag

**Comment by DrDMo** [comment]
What an idiot.

**Comment by shiftingtech** [comment]
I'm locking this, as comments appear to  be becoming personal attacks, rather than productive feedback
