### ISSUE TITLE
STEP file of Voron 2.4r2 has each component stored as unique model, not instance

### ISSUE THREAD

**Issue by KhanSJet** [VoronDesign/Voron-2#350]
Hello Voron Team !
I imported the V2.4r2 STEP file on 2 different CAD software (namely Ansys Spaceclaim and Onshape), and it seems that components are not instancied. I mean that if we have for example 100 M3x8 screws in the build, each one of them has its own 3D model. Instead they should all be instances of the same component.
This issue makes the 3D model of the whole printer unnecessary heavy and laggy. 
It's no showstopper, but I believe it's just a matter of export options in the CAD software that generated the full STEP file.

**Comment by raymondh2** [comment]
If there is an option to do this in Fusion360 we could consider it. But I'm not finding it. It also likely won't work with how our CAD process work. (importing steps made by other developers into Fusion360 making everything in those steps already unique instances.)

**Comment by stvptrsn** [comment]
I don't know of any option like that in F360 either.  I intentionally made them their own instance for BOM counting purposes.  The script I use only counts fasteners if they are "independent".  Unfortunately this seems to be a side effect of that and would take a very large amount of effort to correct.
