### ISSUE TITLE
The FYSEC mini12864 specified in the sourcing guide has the EXP1/2 keyed opposite of the BTT boards

### ISSUE THREAD

**Issue by Steven23456** [VoronDesign/Voron-2#351]
For me this cost several hours and (because I'm impatient) dollars in buying new board/cables trying to figure out why sometimes the pi would detect the MCU over USB and sometimes it wouldn't. As it turs out (at least on the Octopus Pro) the backwards connector on this display was the culprit. 

To help others, maybe just a note on Page 251 about checking the pinout of the board & the display before connecting might save them lot of time and frustration. 

![Untitled](https://user-images.githubusercontent.com/57726602/166148186-67c9462f-8a10-4a74-8896-51299a81b0b2.png)

**Comment by bdbell** [comment]
That is covered in the follow-on documentation.  https://docs.vorondesign.com/build/electrical/mini12864_klipper_guide.html
