### ISSUE TITLE
.f3d Materials and Appearences are disorderly

### ISSUE THREAD

**Issue by ForgeThrall** [VoronDesign/Voron-2#355]
The Physical Materials and Appearances in the .f3d seem to be neglected. There are some entries with multiple duplicates, as well as some completely unused entries. This can be a problem for people who are looking to modify the appearances to test different color pallets.

I am unsure of the work flow to produce the final .f3d provided in the repo, and as such I am wary of submitting a fix for this in the case that it would be more appropriately handled upstream.

**Comment by stvptrsn** [comment]
I think this is a result of how the file has evolved over many years and from importing many different CAD models for things like the Pi and other off the shelf components.  I agree, it has made a mess of the appearance and material settings.  Believe me, I've tried to fix this but the amount of work required for next to no real benefit was not worth it.  If this is easier than I'm aware of I'm open to being educated on how to fix it.  Let me know.
