### ISSUE TITLE
Z banding on front side of print only

### ISSUE THREAD

**Issue by Machine73** [VoronDesign/Voron-2#357]
I know this has been brought up a lot.Here and on other platforms, covering many style of machine, but this was weird for me. On my enders z banding was  an issue with improper bed leveling and tramming, and it affected all sides of the print. Low and behold...easy fix. learn to level properly. Fast forward 2 years, I have built my first voron 2.4 r2. The build was straight forward, got things sorted out and went to print my first test cube, and came across something odd. I have z banding only on the front side of my flow cube. all other sides were flawless. The front was visibly and physically riddled with z banding. When I gauged my sides I was 3.9-4.0 on the back and sides, the front came out 4.6.
I am new to core xy builds and have no clue where to start troubleshooting this issue.

**Comment by raymondh2** [comment]
The issues here on github are generally issues with the design and not user support. Best places for that follows:
Reddit: https://www.reddit.com/r/vorondesign/
Discord: https://discord.gg/voron
