### ISSUE TITLE
mini12864_case_front fillet edge

### ISSUE THREAD

**Issue by whatthefilament** [VoronDesign/Voron-2#360]
When printing a new front case for my V2.4 I noticed that the heat-set inserts are designed to nestle in the front case body when inserting the accent piece. However, the cutouts for the heat-set inserts began halfway down the face making it very difficult to install the accent piece. Simply extending the cutouts up the face made the assembly and fitment much better. 

Wasn't sure how to upload the modified files so here is a link to a repository for them. Please let me know if there is a better way. 

https://github.com/whatthefilament/Voron-2.4-Mods/tree/main/Display%20Panel

![Screen Shot 2022-06-02 at 10 51 20 AM](https://user-images.githubusercontent.com/101848126/171657727-e315a2a8-fbda-4f26-ab51-17cf32ff9d5b.png)

**Comment by stvptrsn** [comment]
The cutout for the heatset inserts have no lips to catch on anything when inserting the accent piece into the main housing so I do not see the need to extend those holes to the front surface.  I would check for print artifacts on your pieces that may be causing you difficulty.

Section analysis showing there are no surfaces that would prevent the accent piece from being inserted into the front piece.
![image](https://user-images.githubusercontent.com/46913624/172193390-791a2e73-c45c-4a87-997d-6701bbf0f348.png)

**Comment by whatthefilament** [comment]
I get what you're saying. 

You can see the cutout fits the insert perfectly. However, when installing the front plate after the insert is installed it has a very hard time getting passed that edge. If that edge is gone. The heat-set insert slides in easily  


![Screen Shot 2022-06-06 at 11 57 33 AM](https://user-images.githubusercontent.com/101848126/172198446-650408e5-df7d-465e-9258-8d9ca011816a.png)

**Comment by stvptrsn** [comment]
Well there's the problem.  You insert the accent piece into the housing THEN insert the heatset while holding those two parts together.

**Comment by whatthefilament** [comment]
That makes sense. I suppose that would work, wouldn't it.

The way I did it felt a bit more intuitive to me and I did it that way because I felt that's how the diagrams in the build guide were illustrating. Maybe there could be a call out in the build guide to make that clear? 

Idono I could be the only one who had that problem. So don't want to make to big of a fuss about it

**Comment by stvptrsn** [comment]
It does call out to hold the pieces together when setting the heatset inserts.
![image](https://user-images.githubusercontent.com/46913624/172202029-4d5e5aed-1c28-4b84-a78a-c6430d59cbec.png)

**Comment by whatthefilament** [comment]
Looks like my guide was corrupted. Which could have been part of the problem too. 

![Screen Shot 2022-06-06 at 12 25 02 PM](https://user-images.githubusercontent.com/101848126/172203186-8f9fcd91-0693-4ccd-bc7b-092168ab0e8c.png)
