### ISSUE TITLE
Afterburner and Probe Bracket heatset holes are 4.8mm instead of the 4.7mm used everywhere else

### ISSUE THREAD

**Issue by ChaosBlades** [VoronDesign/Voron-2#361]
This was fixed on the Afterburner CAD but not the Voron-2 CAD that contains Afterburner. STLs need to be updated as well.
https://github.com/VoronDesign/Voron-Afterburner/issues/15

In addition, the Probe Brackets are 4.8mm instead of 4.7mm as well.

Need to reprint these parts now because the heatset just falls into the hole instead of actually melting in.

**Comment by nemgrea** [comment]
we will not be fixing this as long term the switch to StealthBurner will resolve this. thank you for the report though!
