### ISSUE TITLE
Can the STL for the Z endstop with PCB be included?

### ISSUE THREAD

**Issue by 1980alexGS** [VoronDesign/Voron-2#362]
Sorry if I'm posting this in the wrong place, but it seems the STLs should include a design for when a Z endstop switch PCB is used. A PCB was included in my Formbot kit, it is shown in the build manual, but there is only a single STL in the Voron 2.4 repository under Z_Endstop. It is too tall to accommodate the PCB against the deck.

I nominate this one to include:
https://github.com/hartk1213/Voron-Hardware/tree/9d7398a639b2ad8459318e164e67fb315118936b/Microswitch_Z_Endstop

Cheers

**Comment by raymondh2** [comment]
As those are mods they will not be included in the release files
