### ISSUE TITLE
M3x6 FHCS missing in sourcing guide

### ISSUE THREAD

**Issue by winstonwoff01** [VoronDesign/Voron-2#366]
Pages 227,229 and 232 on the Voron 2.4r2 VERSION 2022-02-19 reference flat head screws to attach the cable chains but the 2.4 Sourcing guide does not mention needing flat head screws.

**Comment by nemgrea** [comment]
added

**Comment by GadgetAngel** [comment]
> added

The sourcing Guide spreadsheet has not been updated

**Comment by GadgetAngel** [comment]
In fact there are discrepancy between the Spreadsheet and the Sourcing Guide.  Please check this over and fix

**Comment by nemgrea** [comment]
i believe you are confusing the BOM and the souring guide, the sourcing guide has indeed been updated

**Comment by GadgetAngel** [comment]
> i believe you are confusing the BOM and the souring guide, the sourcing guide has indeed been updated

You are correct the Sourcing Guide was updated, but now the BOM is not showing all the parts.  Who updates the BOM?  Please let them know the BOM is not in synch with the sourcing guide.  M3x6 FHCS and M3x10 FHCS are both missing from the BOM!

**Comment by nemgrea** [comment]
bom updates are handled through a seperate private repo, 

PR has been submitted for approval that includes the following:
- added m3x6FHCS per PR#366 on V2 repo
- fixed formatting for m3x10 FHCS as they were not displaying

**Comment by GadgetAngel** [comment]
> bom updates are handled through a seperate private repo,
> 
> PR has been submitted for approval that includes the following:
> 
> * added m3x6FHCS per PR#366 on V2 repo
> * fixed formatting for m3x10 FHCS as they were not displaying

Thank you, I will remember that info
