### ISSUE TITLE
2.4R2 assembly manual page 40 text error

### ISSUE THREAD

**Issue by Higlac** [VoronDesign/Voron-2#373]
Page 40 of the 2.4R2 assembly manual reads "The fully assembled Z Drive is highlighted in blue." It is highlighted in orange in the image.
![Screenshot_20220705-141021](https://user-images.githubusercontent.com/18043588/177401222-b60221bd-14f3-4e0b-8365-832c08e45c1f.png)

**Comment by Drachenkaetzchen** [comment]
It's pretty much blue here. Latest Voron v2.r2 Manual.

![image](https://user-images.githubusercontent.com/162974/177550028-a6f0a2ee-73eb-45fb-a83f-0bf7ea821868.png)

**Comment by DunarDolorgiet** [comment]
Thank you for reaching out. The colour is meant to be blue and shows as blue on all devices available to me. Is it possible that you configured a "high contrast mode", "blue light filter" or other accessibility enhancements in your pdf viewer or operating systems?
 
We also publish a version of the manual with higher base contrast ( https://github.com/VoronDesign/Voron-2/blob/Voron2.4/Manual/Assembly_Manual_2.4r2_highcontrast.pdf ).

**Comment by Higlac** [comment]
Interesting... I opened it with the Kindle pdf reader where it was orange and didn't think to check it on another reader. I just opened it in a different app and it shows as blue. I wonder what caused that.
