### ISSUE TITLE
Manual Specifies wrong wire thickness.

### ISSUE THREAD

**Issue by neeamradia** [VoronDesign/Voron-2#378]
Page 210 of the 2.4r2 manual specifies:

'Cables should be at least 1mm^2 (AWG18) or thicker depending on local regulations.'

18AWG = 0.75mm^2
0.1mm^2 = 16AWG?

Which one should it be? 18 or 16 AWG?

![image](https://user-images.githubusercontent.com/67102613/182729867-791092c5-0dc4-4e75-ba4b-3b9504040f8c.png)

**Comment by nemgrea** [comment]
American 18 gauge wire is listed at 0.0403in diameter which is above 1mm. where are you getting .75mm from?

EDIT: i believe you may be looking at cross sectional area of which it would be closer to 0.75 when what is called out in the note is thickness (i.e. diameter)

**Comment by neeamradia** [comment]
> American 18 gauge wire is listed at 0.0403in diameter which is above 1mm. where are you getting .75mm from?
> 
> EDIT: i believe you may be looking at cross sectional area of which it would be closer to 0.75 when what is called out in the note is thickness (i.e. diameter)

Sorry - yes that is likely that I am looking at the wrong dimension.
