### ISSUE TITLE
Keystone panel is only for one size

### ISSUE THREAD

**Issue by TekuSP** [VoronDesign/Voron-2#380]
Keystone panel in R2 is only for one size.
https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/Skirts/keystone_panel.stl

Compare of front skirt 350mm and Keystone Panel:
![image](https://user-images.githubusercontent.com/13198444/185188591-c50f171f-4d88-45f8-844e-2d2e830ec2c4.png)

**Comment by raymondh2** [comment]
It's for all sizes. The rear skirts only have the center piece as different sizes now. This was to simplify unique part count and make it not matter what size printer you are building for PiF..

**Comment by TekuSP** [comment]
Oh yes you are right. I missed that somehow.
On R1 it was front_rear_skirt and here it is only front_skirt and rear middle part is different.

Thanks!
