### ISSUE TITLE
Improvement: Request to add locking Washer in Frame assembly

### ISSUE THREAD

**Issue by tkranz** [VoronDesign/Voron-2#382]
Hi,
I'm building my first Voron with Formbot Kit from Aliexpress.
It is quit complicated to align the frame with the cheap screws, I purchased better quality screws in local hardware shop.
While adding locking washers to the screws it is much but better to align and the screws are secured afterwards.
See the attached picture for details, hope this is the right pace to post this, if not please move and let me know.

Thanks for all who work on this project, amazing work and perfect documented !
Thomas
![modification](https://user-images.githubusercontent.com/6984823/186366983-ec2d0d8b-e631-4c5f-8213-ae3fe78a9b37.jpg)

**Comment by nemgrea** [comment]
this is an issue with a specific KIT manufacturer not the general design overall
