### ISSUE TITLE
Missing ISO and DIN standards and McMaster-Carr link for the M3x6 Flathead screws (FHCS)

### ISSUE THREAD

**Issue by AdamWarnock** [VoronDesign/Voron-2#384]
I'm pricing out a V2.4 r2 build and noticed that there's no McMaster-Carr link for the M3x6 flathead screws. Also, I noticed that there are no ISO or DIN standards listed with the entry. Below I've listed the McMaster-Carr catalog URL and the ISO and DIN standards.
Link to McMaster-Carr entry: [https://www.mcmaster.com/91294A126/](https://www.mcmaster.com/91294A126/)

ISO and DIN standards:
ISO 10642
DIN 7991

**Comment by nemgrea** [comment]
source guide fixed
