### ISSUE TITLE
Bug: Wrong number of "layers" in the graphic

### ISSUE THREAD

**Issue by Sonnenwerk** [VoronDesign/Voron-2#386]
On page 188 picture two (from right) shows one layer (the pcb board). Pictures 3 and 4 show two layers. I think the upper one is wrong.

![image](https://user-images.githubusercontent.com/28840367/190610632-44abe58e-5a7c-4962-bdf8-1be36bd83820.png)

**Comment by raymondh2** [comment]
Looks like it's just missing the chamfer in that view for some reason. It's a minor issue and will be fixed when we get to it.

**Comment by nemgrea** [comment]
2 layers is correct, the PCB version also has a printed part to protect the bottom of the pcb
![image](https://github.com/VoronDesign/Voron-2/assets/52015997/5337ecac-e528-4fd1-b8c5-ba06e3ed96f1)
