### ISSUE TITLE
QR codes and voron.link urls not working in the manual

### ISSUE THREAD

**Issue by Crossbone-fpv** [VoronDesign/Voron-2#387]
Most if not all the QR codes (and the accompanying voron.links urls ) in the manual don not work.

<img width="322" alt="Schermafbeelding 2022-09-16 om 21 57 03" src="https://user-images.githubusercontent.com/57276677/190723584-6ef918b8-0ee9-4823-9397-592e12021d1a.png">

**Comment by raymondh2** [comment]
Can't you verify you don't have anything that would be blocking it. It works fine for me.

**Comment by Crossbone-fpv** [comment]
You're right. I got an DNS_PROBE_FINISHED_NXDOMAIN on my regular network. Switched to my mobile backup G4 network and all links and QR's are working fine.
