### ISSUE TITLE
[Manual] Z drive assembly doesn't mention seating set screws on motor shaft

### ISSUE THREAD

**Issue by loopj** [VoronDesign/Voron-2#398]
Hey folks, absolutely love the manual but wanted to share something I missed on my initial build which could be an opportunity to improve it even further.

For the extruder and belt drive assembly there is a note that says:
> Make sure the set screw in the drive pinion is seated on the flat of the motor shaft.

I think it would be great to say the same thing on page 38 for attaching the pulley to the Z drive shafts.

**Comment by asdasdwa-v02679** [comment]
I think this edit resolves the suggestion. let me know if you meant something different! just in case it does resolve it as is, here is a updated version of the page plus a higher rez of just the edited assembly for the convenience of the Manual team!
![voron 2 page 38](https://github.com/VoronDesign/Voron-2/assets/133813592/bb8e3fc2-429b-4fe3-b667-078c482f1b3d)
![voron 2 page 38](https://github.com/VoronDesign/Voron-2/assets/133813592/411db579-7fac-443d-92e2-626760be831c)
