### ISSUE TITLE
Y-Axis Gantry Page - 89

### ISSUE THREAD

**Issue by KingVeder** [VoronDesign/Voron-2#413]
Minor but the screw/T-Nut on the rail should start on the second one in, on both sides to allow for the Idler M3 & M5 T-Nut
![Screenshot 2023-01-16 202957](https://user-images.githubusercontent.com/34978310/212790844-d19b0978-87c2-40c9-b403-bd0797bc3f6d.png)

**Comment by nemgrea** [comment]
if the directions on page 88 are followed all of the T-nuts fit properly as shown.

![Capture](https://user-images.githubusercontent.com/52015997/213299606-8898391f-2f4c-4ed1-9b65-e12593f2aeff.PNG)

**Comment by newphreak** [comment]
This is very much a real issue on 300mm builds. I forget the math, but i think the 50mm difference from the 300 and 400mm rails is what makes the 300 (350mm rail) have less space here.

**Comment by andreasbeh** [comment]
Can confirm this issue exists on a 300mm build, I am about 5mm short each end from being able to fit a M5 ball-spring nut. It fits just fine with a slide-in style nut, though that needs double checking for a 250mm build.
![image](https://user-images.githubusercontent.com/73668363/228207665-1db50433-8eea-4d11-bd5a-3e4f5e2a2c18.png)

EDIT: The configuration in the pictures does NOT work, the ball-spring nut needs to be flipped around (so hole towards the rail), then it fits with a screw in the last hole of the rail, and a slide-in M5 nut for the end

**Comment by asdasdwa-v02679** [comment]
hello friends, I hope this edit solves the problem :) let me know if it needs to be changed! 

 full page : ![voron 2 page 88](https://github.com/VoronDesign/Voron-2/assets/133813592/2340dfd2-264b-4b0c-8219-745ea4e57da1)
