### ISSUE TITLE
suggestion：Use the bottom of the probe to trigger the Z Endstop, not the nozzle。

### ISSUE THREAD

**Issue by fanhualei** [VoronDesign/Voron-2#415]
suggestion：Use the bottom of the probe to trigger the Z Endstop, not the nozzle。

* The nozzle is too small to trigger the Z Endstop
*  the nozzle is easy to carry excess filament ,This will trigger the Z Endstop in advance
* The Z Endstop is too close to the hot bed. When placing the PEI board, the Z Endstop will be accidentally covered.

After transformation

![a](https://user-images.githubusercontent.com/34436863/215780369-f9fbc710-1128-4aba-9f0c-f10604f77dd9.jpg)
![b](https://user-images.githubusercontent.com/34436863/215780422-afea9603-854a-4804-af23-b36a1ba21685.jpg)

**Comment by bdbell** [comment]
The intent of probing on the nozzle is to account for changes in Z height that occur when changing hot ends or nozzles.  To trigger on the probe body eliminates that compensation.

**Comment by valadas** [comment]
With some nozzles, the nozzle might touch the bed before the probe reaches the switch. Also, I don't want to speak out of order but I think the whole idea of having a z switch may be obsolete given how good Voron TAP works :) Maybe for the next release it becomes the standard...
