### ISSUE TITLE
Design interference of bottom_panel_clip_x4 with side_fan_support_x2

### ISSUE THREAD

**Issue by ReXT3D** [VoronDesign/Voron-2#416]
I am somewhat surprised that this has not been previously reported.  It seems to be present since the 2.4R1.  I guess not many people actually install the bottom electronics panel...

![image](https://user-images.githubusercontent.com/77699888/219811904-94bf4a1d-fbcf-4290-b621-b7984009dd1b.png)

**Comment by nemgrea** [comment]
fixed
https://github.com/VoronDesign/Voron-2/pull/419
