### ISSUE TITLE
Marlin instead of reprap

### ISSUE THREAD

**Issue by holymoly** [VoronDesign/Voron-2#417]
The slicer containing the gcode flavor for reprap firmware. 
Shouldn't this be Marlin?

**Comment by valadas** [comment]
Actually, it should be Klipper...

**Comment by holymoly** [comment]
Only for SS. There is no Klipper in PS.

**Comment by valadas** [comment]
Haaa, that would explain it then

**Comment by nemgrea** [comment]
Q and A, not issue related. closing
