### ISSUE TITLE
BOM - Wrong length for DIN 3 Rails

### ISSUE THREAD

**Issue by EmJay276** [VoronDesign/Voron-2#420]
Hi,
I tried some custom size in the configurator and noticed the DIN Rails scale with the wrong axis.
They should scale with the X-Axis, but scale with the Y-Axis.

I used X x Y x Z - 300 x 600 x 280 (buildvolume), so the DIN Rails should stay the length of the 300x300 printer (415 mm)
But they scaled to 715 mm in the BOM list.

![grafik](https://user-images.githubusercontent.com/8619525/224506170-6997d722-25cb-4a1b-913b-ef01e8acb739.png)

**Comment by nemgrea** [comment]
fixed
