### ISSUE TITLE
A/B Belts Page 140 wrong Screw Size/Picture

### ISSUE THREAD

**Issue by Flol0** [VoronDesign/Voron-2#422]
Hi, on page 140 in the Manual it should be a M3x30 SHCS in the top: https://raw.githubusercontent.com/VoronDesign/Voron-2/Voron2.4/Manual/Assembly_Manual_2.4r2.pdf
The M3x40 is too long an is exposed on the right side of the carriage.

In the Stealthburner Manual on page 61it`s a M3x30 SHCS but the picture is still showing a longer screw than the bottom one.(I think it`s a picture of the M3x40 SHCS

**Comment by asdasdwa-v02679** [comment]
Good catch, here is a updated version of the page plus a higher rez of just the edited assembly for the convenience of the Manual team!
![voron 2 page 140](https://github.com/VoronDesign/Voron-2/assets/133813592/f8c77e13-6d1c-4ddf-812b-5becde2ac191)
![voron 2 page 140](https://github.com/VoronDesign/Voron-2/assets/133813592/de36615e-00ba-45b8-8953-6b4cc8b5c1e0)
