### ISSUE TITLE
Manual - T-nuts not mentioned when assembling main frame

### ISSUE THREAD

**Issue by orotecluc** [VoronDesign/Voron-2#424]
in the manual, when assembling the main frame, nowhere is it mentioned to already insert T-nuts vor the Z-rails or the Z-motors.
It would be nice to have an editable version of the manual so I can update the manual with my own findings and then have it send to you for pull request.
Want to help making the manual more like the prusa instructions, which are really complete and help with not having to disassemble half the printer when you find out some t-nuts need to be inserted when the rails are already closed by fixind them.

Kind regards

**Comment by timmit99** [comment]
Hi @orotecluc,
     The T-Nuts we specify for the printer are roll-in's and therefore are designed to, and can be, inserted into the frame even when both ends are completely closed. As such, and per the note at the beginning of the manual, t-nuts are not going to be called out explicitly. Build size determines the length of rails as well as other features that dictate the number of t-nuts used in each individual build. If you are trying to thread a bolt into the slot of an extrusion and there's not already an existing threaded feature there then you need to install a roll in t-nut.
