### ISSUE TITLE
Assembly Manual Page 97 Right XY joint has circle on the wrong M5 hole

### ISSUE THREAD

**Issue by ntchris** [VoronDesign/Voron-2#428]
Assembly Manual Page 97 Right XY joint has circle on the wrong M5 hole

in the Voron-2.4 R2 assembly manual,  version 2022-07-04
https://raw.githubusercontent.com/VoronDesign/Voron-2/Voron2.4/Manual/Assembly_Manual_2.4r2.pdf
Page 97, 

Right XY joint
in the right most side image , there is a circle on the wrong M5 hole and Hex nut.
the correct hole should be the hole above of the wrong one.
please see the attached picture

Thanks!
![wrong_hole_page97](https://user-images.githubusercontent.com/15345990/233852926-9780663e-ed31-4971-ba84-787cd6890760.jpg)

**Comment by asdasdwa-v02679** [comment]
Good catch, here is a updated version of the page plus a higher rez of just the edited assembly for the convenience of the Manual team! 

![Assembly_Manual_2 copy](https://github.com/VoronDesign/Voron-2/assets/133813592/fa4ee292-0bdd-4064-875f-00b7aa193636)

![voron2 xy joint right](https://github.com/VoronDesign/Voron-2/assets/133813592/fd274ef3-2387-46d6-8fd6-013347788aea)
