### ISSUE TITLE
T-Nut not fitting - Manual page 90

### ISSUE THREAD

**Issue by miracuruzrh** [VoronDesign/Voron-2#430]
Hi

I ordered from a chinese seller a kit for the Voron 2.4 350mm version.
In the manual there is a problem at page 90 -93 where the Front idlers / Z-Joint should be assembled with the T-Nuts.
The mentioned T-Nuts can't be installed this way, because the M3x8 screw and T-Nut from the MGN9 Linear rail is blocking the nut already.
The only way to install both T-Nuts was for me to turn them 180° and cut the outer T-Nut in half so that it did not overlap.
I have made a drawing which shows the problem, where T-Nut 1 and T-Nut 2 are overlapping.

Now is my question. Should this be mentioned in the manual, or did I something wrong for the 350mm version?
[Voron r2.4.pdf](https://github.com/VoronDesign/Voron-2/files/11408300/Voron.r2.4.pdf)

Here I have just added my workaround
[Voron r2.4 Workaround.pdf](https://github.com/VoronDesign/Voron-2/files/11408596/Voron.r2.4.Workaround.pdf)

**Comment by nemgrea** [comment]
duplicate issue
#413
