### ISSUE TITLE
Cura 5.3.1 worngly slices pcb_din_clip_x3

### ISSUE THREAD

**Issue by Shchava** [VoronDesign/Voron-2#432]
I encountered a bug in new cura release, where it fills a gap that should be empty in din clip. Cura 5.2 slices it normally.  
I think it makes sense to make that gap a bit bigger and update stls to prevent such things from happening. 

![image](https://github.com/VoronDesign/Voron-2/assets/28152150/e2de85a7-8ada-42b7-9c41-934d0ce77642)
![image](https://github.com/VoronDesign/Voron-2/assets/28152150/68cdb7d4-5536-494b-bd2f-56647926e1fa)

**Comment by nemgrea** [comment]
unfortunately this seems like more of a slicer issue than an issue with the stl.
