### ISSUE TITLE
No assembly CAD file for Voron 2.4 300mm

### ISSUE THREAD

**Issue by OlderGrand** [VoronDesign/Voron-2#433]
Hello,
I would like to make some modifications to the Voron 300mm skirt. Unfortunately I can only find the assembly CAD file of the Voron 250, where can I find it for the Voron 300mm?

**Comment by raymondh2** [comment]
Only the assembly for the 250mm Voron 2 exists. All other models are calculated from the base for part lengths

**Comment by julianschill** [comment]
The 300mm and 350mm skirts are in the 250mm CAD assembly, but hidden. You can unhide them to modify them.
