### ISSUE TITLE
Voron 2.4 300mm-Como saber los colores y cantidades de cada pieza para imprimir en ABS

### ISSUE THREAD

**Issue by Verart3d77** [VoronDesign/Voron-2#441]
Voron 2.4 300mm
 Buenas tardes, favor de indicar cuantas cantidades de cada pieza se imprime y de que color de filamento ABS si es negro o rojo ...Eso no está claro en la carpeta de STL

**Comment by julianschill** [comment]
This is clarified in the manual and the documentation page: https://docs.vorondesign.com/sourcing.html#colors-and-quantities

**Comment by nemgrea** [comment]
also colors are covered here
![image](https://github.com/VoronDesign/Voron-2/assets/52015997/8c51a524-fb4a-477f-b12a-9f7cd8eda040)
