### ISSUE TITLE
Assembly Manual Page 182 - wire - swapped colour from inlet

### ISSUE THREAD

**Issue by okovjogurtu** [VoronDesign/Voron-2#446]
Assembly manual Page 182 - wire - swapped color from AC input, brown should be on left side, blue on right side.

**Comment by Sigi-cz** [comment]
There is no issue in the manual.

@okovjogurtu Not sure what version of manual You use, but the current version ([e47cc70](https://github.com/VoronDesign/Voron-2/commit/e47cc70edbdb0c36916885b54a5e1f30f52a717a)) states:
"We show the wiring in the IEC colour scheme.
Depending on your region the colour scheme and
wiring standards will differ."

The "Filtered Inlet" on page 156 is male plug (confusing, but true) and the colors are correct.
[https://www.electronics2000.co.uk/pin-out/iec.php](https://www.electronics2000.co.uk/pin-out/iec.php)
