### ISSUE TITLE
M4 knurled nut dimensions

### ISSUE THREAD

**Issue by skelder** [VoronDesign/Voron-2#455]
I wanted to know the exact height of the m4 knurled nut mentioned in the manual.

Searching for the DIN-466-b returns this [link](https://www.fasteners.eu/standards/DIN/466/)

is this the correct one?

As i could not find the exact thing to buy I am thinking about replacing it with few other m4 threaded nuts stacked together to get the required height.

**Comment by julianschill** [comment]
The one from your link is the right one. The exact height doesn't matter, as long as all four are the same. It is used as spacers between the frame and the bed.

**Comment by skelder** [comment]
Thank you for clarifications!
