### ISSUE TITLE
BOM list export

### ISSUE THREAD

**Issue by tristelune** [VoronDesign/Voron-2#457]
Hello

On the main Voron web site, there is an issue with the exported BOM list of the Voron 2, due to the fact the csv file is comma separated, and in some lines there is text with comma like this one (extract from the csv file directly):
Cables,Nylon Cable Ties, Small (.07-.10", 1.8-2.7mm wide),42,

This text should be in one cell :
Small (.07-.10", 1.8-2.7mm wide)

but it is split in two cell due to the comma inside it, messing with the table when imported in open office, and probably also in excel.

To solve it, all the BOM lists should be exported using semicolon, or forbid the usage of comma in cell.

Thanks

**Comment by nemgrea** [comment]
fixed

**Comment by tristelune** [comment]
Hello

Just tested to import the bom list after the fix and it's work perfectly now.

Thanks for change
