### ISSUE TITLE
Defualt Min Extruder Temp is Problematic

### ISSUE THREAD

**Issue by sirbrialliance** [VoronDesign/Voron-2#459]
In Voron2_Octopus_Config.cfg, and perhaps others, the default extruder min_temp is 10° C. If you store your printer in a cool, but not freezing, location, this can trip you up when the printer suddenly stops working in the winter.

Real-life issue I had (my config is customized, but the min_temp default is unchanged):
![min_temp](https://github.com/VoronDesign/Voron-2/assets/1445189/0d64a949-bea2-4ad5-a527-a5d834270955)

**Comment by julianschill** [comment]
I don't think that's a problem. Most printers don't experience such low temperatures and for those who do the minimum temperature can easily be changed. 
The minimum temperature is a security feature to catch bad thermistors or wiring so I wouldn't change it in the default config.

**Comment by sirbrialliance** [comment]
That's an understandable position.
The tricky thing is that it's not likely to come up while you're setting up the printer. Perhaps a comment pointing out that this default may not be a good value if you store your printer in a cold location would be the best way to address this?

**Comment by thijstriemstra** [comment]
> Most printers don't experience such low temperatures and for those who do the minimum temperature can easily be changed.

In winter my printer reaches 6 celsius in room it's stored. I changed min_temp to 12 (matching my prusa mini) and heat up room until 12 has been reached, before turning printer on.
