### ISSUE TITLE
voron enclosure 2.4 where are the files?

### ISSUE THREAD

**Issue by rada30** [VoronDesign/Voron-2#463]
good morning. 
 Where the voron 2.4 350 enclosure files are located. That is, doors and sides

**Comment by julianschill** [comment]
Panels are in the drawings folder. There are DXFs and PDFs. https://github.com/VoronDesign/Voron-2/tree/Voron2.4/Drawing_DXFs/Panels
Doors, sides and top are just rectangles. Check the configurator on the homepage for dimensions.

**Comment by valadas** [comment]
Those are just rectangular and you simply get the dimensions from the configurator here https://vorondesign.com/voron2.4

**Comment by rada30** [comment]
Okay .  Okay, what's found.  It's just that he didn't see the sizes of the doors and sides.  And by telling me in the settings.  I already saw it.
