### ISSUE TITLE
Incorrect hole type in left XY-Joint for Bearing Stack

### ISSUE THREAD

**Issue by bukshanekom** [VoronDesign/Voron-2#466]
The left and right XY-Joints mirror each other in terms of the bearing stack and the GT20 idler.
The bolts which holds the GT20 idler screws directly into the plastic, whereas the bolt holding the bearing stack is held in place with a M5 nut at the bottom.
The problem is that the left hand part has the GT20 pulley and bearing needs to swopped around as the current holes are incorrect for the GT20 idler.  

<img width="698" alt="Left XY Joint Wrong Holes" src="https://github.com/VoronDesign/Voron-2/assets/5247502/1fc55b89-213a-4058-8067-0f11c140ffc8">

https://github.com/VoronDesign/Voron-2/assets/5247502/56ad289d-b4ce-476d-8eba-c67216c0205a

**Comment by hartk1213** [comment]
> The left and right XY-Joints mirror each other in terms of the bearing stack and the GT20 idler. The bolts which holds the GT20 idler screws directly into the plastic, whereas the bolt holding the bearing stack is held in place with a M5 nut at the bottom. The problem is that the left hand part has the GT20 pulley and bearing needs to swopped around as the current holes are incorrect for the GT20 idler.
> 
> <img alt="Left XY Joint Wrong Holes" width="698" src="https://private-user-images.githubusercontent.com/5247502/307771302-1fc55b89-213a-4058-8067-0f11c140ffc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIyMzQsIm5iZiI6MTcwOTA1MTkzNCwicGF0aCI6Ii81MjQ3NTAyLzMwNzc3MTMwMi0xZmM1NWI4OS0yMTNhLTQwNTgtODA2Ny0wZjExYzE0MGZmYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTYzODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBiODRjYzVjNzlmYTdmZWQ4NDZiOGVhOTU5ZDRjOGI0Nzg1ZGUzYzcxZTQ0ODIwYTgzY2MzNjU2MDYwOWYxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cXQSns3FC4LrFcGrhkl-O1FDKnwtpHVIM6dKPjxr7W4">
>  Left-XY.Joint.Wrong.Holes_480p.mov

![image](https://github.com/VoronDesign/Voron-2/assets/12398294/028d7d3f-8964-4fb6-a1fc-daa067130ca1)
looks like you have the bearing stack in the wrong location ..the toothed idlers go in the front on both sides 
so in that case both toothed idlers have the same thread into plastic while bearings both use m5 nut

![image](https://github.com/VoronDesign/Voron-2/assets/12398294/24386923-a6d7-4306-bb48-03bd0a818401)
![image](https://github.com/VoronDesign/Voron-2/assets/12398294/4cfe6532-f458-4683-bb4c-adba6c298c65)
