### ISSUE TITLE
BOM/sourcing guide: M4x6 BHCS, update x4 to x7.

### ISSUE THREAD

**Issue by pkpk2** [VoronDesign/Voron-2#467]
The sourcing guide says only x4 of M4x6 BHCS are required, but according to the latest manual we need x7:

* x4 for PSU mounts (page 153)
* x2 for Solid State Relay mount (page 157)
* x1 for PSU stabilizer (page 169)

**Comment by julianschill** [comment]
The BOM says 7. Sourcing guide is just a link list, that also doesn't respect the settings in the configurator. So you always should use the BOM for sourcing and not rely on the sourcing guide.
Nevertheless it should be corrected in the sourcing guide (or the amounts removed completely).

**Comment by nemgrea** [comment]
sourcing guide has been updated, thank you!
