### ISSUE TITLE
Manual Page 33 "M5 Shim" can be ambiguous

### ISSUE THREAD

**Issue by Altirix** [VoronDesign/Voron-2#475]
This should be explicit and state "M5 Shim 1mm" as there are two types of M5 Shim in the fysetc fastener pack for V2.4 (1mm, 1.5mm)

![Screenshot_27](https://github.com/VoronDesign/Voron-2/assets/19439141/eb4c952e-d24a-4215-89a6-e1975ba8ea23)

the CAD must be opened to confirm what shim this references.

![Screenshot_28](https://github.com/VoronDesign/Voron-2/assets/19439141/804e69c3-d2a1-4ef8-bce0-e0957bd32c09)

**Comment by Altirix** [comment]
seems these 1.5mm shims are only included by fysetcs fastener kit and are not part of the official BOM.

ill keep this up as i think it does still raise a genuine question on the ambiguity when many vorons are built using these kits

**Comment by nemgrea** [comment]
what fystech chooses to include or not include in their kits is their responsibility. our hardware page at the beginning of the manual adequately covers the m5 shim definition and where they can be found, also 1.5mm shims are not part of the voron bom so their inclusion in the fysetc kit cannot be controlled or managed by us.

![image](https://github.com/VoronDesign/Voron-2/assets/52015997/5826102c-01e7-4a64-af49-5f099d478747)
