### ISSUE TITLE
I want to edit some parts, what software should I use? The files in the CAD folder cannot be edited when opened.

### ISSUE THREAD

**Issue by jackshi618** [VoronDesign/Voron-2#478]
I want to edit some parts, what software should I use? The files in the CAD folder cannot be edited when opened.

**Comment by hartk1213** [comment]
@jackshi618 what software are you using to open them? 

The .f3d is a native fusion360 file, 
The .step file is a more universal CAD file that can be opened in most CAD software 

Fusion 360 or onShape are probably your 2 best bets to use at the moment

**Comment by catalinalb** [comment]
Good day, I am tring to open the STEP file in Solidworks Professional 2020 and in Solidworks Maker 2024. 
No succes, I have plenty of RAM and latest i7....
Could someone check this? 

Thank you

**Comment by wolfgangmauer** [comment]
Opening the STEP file with FreeCAD doesn't cause any problems

**Comment by TheLexoPlexx** [comment]
> Good day, I am tring to open the STEP file in Solidworks Professional 2020 and in Solidworks Maker 2024. No succes, I have plenty of RAM and latest i7.... Could someone check this?
> 
> Thank you

No issues in Solidworks 2024 and I've used 2020 before.

**Comment by catalinalb** [comment]
I had to open the STEP file in FreeCAD, export it as a new STEP file. Only then, Solidworks was able to open it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
