### ISSUE TITLE
Incorrect parts STL's for XY Joints.

### ISSUE THREAD

**Issue by QTronics** [VoronDesign/Voron-2#484]
STLs/Gantry/X_Axis/XY_Joints/xy_joint_right_lower_MGN12.stl and STLs/Gantry/X_Axis/XY_Joints/xy_joint_left_lower_MGN12.stl are stl's for MGN9H.

**Comment by hartk1213** [comment]
> STLs/Gantry/X_Axis/XY_Joints/xy_joint_right_lower_MGN12.stl and STLs/Gantry/X_Axis/XY_Joints/xy_joint_left_lower_MGN12.stl are stl's for MGN9H.

do you have a screenshot to show how they are the wrong files?

**Comment by QTronics** [comment]
My error. I thought they were for using and MGN12 on the Y Axis. Not that they were for using an MGN12 on the X Axis and MGN9 on the Y

**Comment by hartk1213** [comment]
ah ok yeah its MGN12 on X and stil MGN9 on Y ill close this since its a non issue 👍🏻
