### ISSUE TITLE
+20mm XY Bridges

### ISSUE THREAD

**Issue by milesale** [VoronDesign/Voron-2#70]
Holes for +20mm XY Bridges do not line up with mating part. Upon investigation, it appears the v2.1 and v2.2 parts are swapped:

`STLs/VORON2.1/ZipChain/XY/v21_xy_bridge_+20mm_x1_Rev2.STL`
`STLs/VORON2.2/ZipChain/XY/xy_bridge_+20mm_x1_Rev2.STL`

**Comment by FHeilmann** [comment]
Thanks for your report. We'll investigate and fix it ASAP!

**Comment by john--** [comment]
Confirmed. Thanks @milesale !

**Comment by FHeilmann** [comment]
fixed by PR #71
